# Site settings
title: ZHPMATRIX blog
email: 
description: "A master in computer science"
baseurl: ""

lifeurl: "life"
nav_life: 日常
url: "http://zhpmatrix.github.io"
github_username:  zhpmatrix

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
